### ISSUE TITLE
"With over six Microsoft certifications offered"

### ISSUE THREAD

**Issue by rezafouladian** [team3192/thstechteam#16]
"With over six Microsoft certifications offered"
"over six Microsoft certifications"
"over six"

...

So what, 6.3 certifications?

**Comment by ghost** [comment]
7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, or ...
